name: Publish docker image

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Compute version
        shell: bash
        id: get-version
        run: |
          IFS="."
          full_version=$(cat version.txt)
          if [[ $full_version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
          fi

          echo "major_version=${major}" >> $GITHUB_OUTPUT
          echo "minor_version=${major}.${minor}" >> $GITHUB_OUTPUT
          echo "full_version=${full_version}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: true
          file: agent/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: |
            linux/arm64
            linux/amd64
          tags: |
            laravelphp/nightwatch-agent:v${{ steps.get-version.outputs.full_version }}
            laravelphp/nightwatch-agent:v${{ steps.get-version.outputs.major_version }}
            laravelphp/nightwatch-agent:v${{ steps.get-version.outputs.minor_version }}
            laravelphp/nightwatch-agent:latest
